### ISSUE TITLE
More CSS Fonts tests

### ISSUE THREAD

**Issue by Ms2ger** [w3c/csswg-test#1000]
Suggested tests to write for CSS Fonts at Test the Web Forward Tokyo:

Simple tests:

Test parsing of the `@font-face` rule (chapter 4). Try various combinations of descriptors, and get them using JavaScript. (E.g. using `document.styleSheets[0].cssRules[0].cssText`).

Moderate tests:

Look in https://github.com/mozilla/mozilla-central/tree/master/layout/reftests/ and https://github.com/mozilla/mozilla-central/tree/master/layout/style/test (search for "font") for Mozilla tests that can be converted to W3C tests to check the spec.

Difficult tests:

Chapter 6-7 about Font Features.

Notes:

In Mozilla's repository, layout/style/test/property_database.js has a property reference you can use instead of reading the spec.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5475; please continue all discussion there.
