### ISSUE TITLE
[css-grid] List of directories per spec section

### ISSUE THREAD

**Issue by tomalec** [w3c/csswg-test#1013]
@mrego You have mentioned that at https://github.com/w3c/csswg-test/tree/master/css-grid-1 you're 
> creating one directory per section of the
spec: https://drafts.csswg.org/css-grid/

As it does not match 1:1 to spec, it was not clear to me witch directory points to which section, until I get through the tests inside.

Maybe it could be done more explicitly, like:
```
3_Grid-Containers
4_Grid-Items
5_Explicit-Grid
...
```
Then it would be obvious to which section they point, it would easier to distinguish 'per section' tests from 'advanced use cases' or just support/reference/tools folders.

**Comment by mrego** [comment]
I was using the "id" (anchor) of each section:
* *3. Grid Containers*: [`grid-model`](https://drafts.csswg.org/css-grid/#grid-model)
* *4. Grid Items*: [`grid-items`](https://drafts.csswg.org/css-grid/#grid-items)
* *5. The Explicit Grid*: [`grid-definition`](https://drafts.csswg.org/css-grid/#grid-definition)
* ...

Main reason is that IMHO the "id" of each section has less chances to be modified compared to the name of the section.

Using the number doesn't seem a good idea, as the sections sometime are moved/added/removed and that would imply we've to do a big rename in the repo.

Anyway, if you still think it's confusing we can try to use directly the names of the sections instead.
Please, let me know your opinion.

**Comment by tomalec** [comment]
Ok, that makes sense .
Maybe we could then put small README.md in here to explain that, link folders to spec sections, with names, so in case of spec change we would need to change only the README, but in everyday use it would be easy to navigate?

**Comment by mrego** [comment]
Good idea, we can even link the [test plan](http://test.csswg.org/source/css-grid-1/test-plan/) in the `README`.
