### ISSUE TITLE
Add licence for NotoSansDeseret-Regular.ttf 

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-test#1044]
This was added in https://github.com/w3c/csswg-test/commit/dcf33c61a971be740b3aa6c90cf53019a340cc7c. To be consistent with every other font, we really should copy the licence over, to make it clear at a glance what license it is under.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5478; please continue all discussion there.
