### ISSUE TITLE
Tests for SVGMatrix, WebKitCSSMatrix

### ISSUE THREAD

**Issue by Ms2ger** [w3c/csswg-test#1064]
https://drafts.fxtf.org/geometry/#svgmatrix
https://drafts.fxtf.org/geometry/#webkitcssmatrix

Some links:

https://github.com/whatwg/compat/issues/2
https://github.com/whatwg/compat/issues/19
https://github.com/whatwg/compat/issues/30
https://github.com/whatwg/compat/issues/32
https://github.com/whatwg/compat/issues/33
https://github.com/whatwg/compat/issues/34
https://github.com/whatwg/compat/issues/35
https://github.com/whatwg/compat/issues/36
https://bugzilla.mozilla.org/show_bug.cgi?id=717722

See also `work-in-progress/microsoft/CSS3/transforms/transform-cssmatrix-*.xht`.

CC @miketaylr, @foolip, @zcorpan

**Comment by zcorpan** [comment]
@peterjoel are you interested in this also?

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5479; please continue all discussion there.
