### ISSUE TITLE
HTML files in UTF-8 need to have 'meta charset=utf-8' 

### ISSUE THREAD

**Issue by jungshik** [w3c/csswg-test#1071]
Some html files are in UTF-8 (beyond ASCII) but do not have 'meta charset=utf-8'. 

XHTML (strict) files do not need that (xml encoding=utf-8) because the default is UTF-8. 

However, html files do need 'meta charset=utf-8' added.  In a lot of cases, the test results are not affected because non-ASCII characters are in meta, link (reviewer's name)  or comment but not in the actual contents. Nonetheless, it'd be better to label them properly. 

For instance, 
https://github.com/w3c/csswg-test/blob/master/css-writing-modes-3/table-progression-vlr-001.html

has the following line:

```html
<link rel="reviewer" title="Gérard Talbot" href="http://www.gtalbot.org/BrowserBugsSection/css21testsuite/">
```

@kojiishi @fantasai

**Comment by gsnedders** [comment]
In *principle* the status-quo is that the testsuite relies upon Apache and its .htaccess files; note in the root directory https://github.com/w3c/csswg-test/blob/master/.htaccess which makes the default character set for all files UTF-8 (and should be sent in the HTTP headers).
