### ISSUE TITLE
Using flexbox + padding results in Firefox and Chrome inconsistency

### ISSUE THREAD

**Issue by frewsxcv** [w3c/csswg-test#1088]
Forgive me ahead of time for filing this here. I've noticed an inconsistency with Firefox and Chrome. I'm not sure who is following the spec correctly. I opened an issue here in case there was any interest in creating a regression test. If there's no interest, feel free to close this.

```html
<style>
body {
  margin: 0;
}

#a {
  display: flex;
  flex-direction: column;
  background-color: grey;
}

#b {
  background-color: black;
  min-height: 30px;
  padding-top: calc(100%);
  width: 180px;
}
</style>

<div id=a>
  <div id=b></div>
</div>
```

<img width="982" alt="screen shot 2016-05-11 at 1 07 42 pm" src="https://cloud.githubusercontent.com/assets/416575/15189570/7630794e-1779-11e6-9bcd-b524db81241f.png">

![screen shot 2016-05-11 at 1 08 09 pm](https://cloud.githubusercontent.com/assets/416575/15189571/7739a6c6-1779-11e6-932e-d13253bf96d3.png)

**Comment by gsnedders** [comment]
cc: @tabatkins @fantasai

**Comment by cbiesinger** [comment]
Are you sure this is calc-related and not just the well-known difference that Blink calculates percentage paddings always relative to widths (like for regular blocks) and that Firefox doesn't?

https://drafts.csswg.org/css-flexbox/#item-margins

**Comment by frewsxcv** [comment]
You're right. This exemplifies the same behavior:

```html
<style>
body {
  margin: 0;
}

#a {
  display: flex;
  flex-direction: column;
  background-color: grey;
}

#b {
  background-color: black;
  min-height: 30px;
  padding-top: 100%;
  width: 180px;
}
</style>

<div id=a>
  <div id=b></div>
</div>
```

> Are you sure this is calc-related and not just the well-known difference that Blink calculates percentage paddings always relative to widths (like for regular blocks) and that Firefox doesn't?

Does the spec have a say about this difference?

**Comment by cbiesinger** [comment]
Spec allows either behavior, see the link I pasted above.

**Comment by frewsxcv** [comment]
Nevermind, I just noticed the spec says to avoid using percentage padding with flex items. It's really unfortunate that the spec doesn't have a say on the issue. Could cause lots of headaches for web developers in the future.

**Comment by frewsxcv** [comment]
Thanks for the quick responses, sorry for the noise.

**Comment by cbiesinger** [comment]
There is longstanding disagreement between implementors on what the spec should say and so it ended up with allowing both behaviors.
