### ISSUE TITLE
css21/borders/border-color-005-ref.xht is broken

### ISSUE THREAD

**Issue by hrj** [w3c/csswg-test#1096]
If I am not mistaken, the intermixing of `px` and `em` units breaks the widths and alignments.

Chromium screenshot:

![border-color-005-ref](https://cloud.githubusercontent.com/assets/345879/16720612/aaccda9c-4755-11e6-87a1-6c115ca83030.png)

Firefox is similar.

**Comment by hrj** [comment]
cc @rhauck (original commiter).

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5483; please continue all discussion there.
