### ISSUE TITLE
Many tests rely on font-size and margin being set from useragent-style-sheet

### ISSUE THREAD

**Issue by hrj** [w3c/csswg-test#1097]
As discussed on IRC,

Take xhtml1/border-width-005.xht for example. The margin in the top text of the file factors into the result. See screenshot:

![css21margin](https://cloud.githubusercontent.com/assets/345879/17075737/fc9dd9ca-50ba-11e6-9ed1-a57b8b8668d8.png)

The margin of the highlighted element is in `em` units and doesn't collapse with the margin of the following element. The test assumes that this margin will be computed to 16px. Hence the test passes only when font size is 16px and the user-style-sheets sets the margin of `p` element to 1em.

I think this affects more than 81 tests. I will try to enumerate them in a follow-up comment.

**Comment by Ms2ger** [comment]
This is expected, though I'm not sure it's written down anywhere. @plinss might know.

**Comment by plinss** [comment]
Only tests with the 'userstyle' flag should rely on a user style sheet being set, and those that do are generally testing user style sheet behavior. There are other assumptions that are relied upon that are documented in the test suite index: http://test.csswg.org/suites/css21_dev/nightly-unstable/ (and used to be documented on the wiki, not sure if they survived elsewhere). A 16px value for the 'medium' font-size is a normal assumption,

**Comment by hrj** [comment]
Ah, so the tests expect a medium font-size of 16px. The only problem then is the assumption that `margin-bottom` of `p` element computes to `1em`.

Either that could be documented or the tests could set the margin explicitly.

**Comment by gsnedders** [comment]
@plinss This is the UA style sheet that's in question here, not the user style sheet.

So yes, either we need to assume the margin is 1em or fix these tests. The font-size is relied on in enough places, though I don't object to people trying to fix this.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5484; please continue all discussion there.
