### ISSUE TITLE
[meta] Get GitHub as the only read/write source for the repo and issues

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-test#1101]
- [x] get the repo and PRs from known good users mirrored somewhere (likely css.w3c-test.org) // @sideshowbarker @deniak 
- [ ] figure out some way of importing all issues in Shepherd into GitHub (do we want to do this here if we're then going to merge this into web-platform-tests? we should check if there's any way to move issues en-mass)

I'm sure I'm missing something that was mentioned before. @plinss?

**Comment by gsnedders** [comment]
We now have http://csswg-test.org/ with http://csswg-test.org/submissions/ containing PRs

**Comment by frivoal** [comment]
How is "good users" defined? write access to the csswg-test repo?

**Comment by gsnedders** [comment]
@frivoal I believe so.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5485; please continue all discussion there.
