### ISSUE TITLE
Missing HTTP headers in css21/i18n/syndata/support?

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-test#1114]
cc @r12a 

_Most_ of the CSS files [here](https://github.com/w3c/csswg-test/tree/master/css21/i18n/syndata/support) have headers provided in `.htaccess` (and soon `.headers` files), but not all. I suspect all should?

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5490; please continue all discussion there.
