### ISSUE TITLE
matchMedia.html uses assert_inherits to test a global property

### ISSUE THREAD

**Issue by jdm** [w3c/csswg-test#1131]
This looks wrong, since properties of the global are expected to be own properties, unlike every other kind of DOM object.

```
test(function(){
    assert_inherits(window, "matchMedia");
}, "window.matchMedia exists");
```

**Comment by gsnedders** [comment]
This is `cssom-view-1/matchMedia.xht`.

**Comment by gsnedders** [comment]
Really much of this file should just be replaced with something using `idlharness`, and then that fixes this.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5493; please continue all discussion there.
