### ISSUE TITLE
Move `display:run-in` tests out of CSS2.1 tests?

### ISSUE THREAD

**Issue by hrj** [w3c/csswg-test#1132]
I am not very familiar with this, but from a cursory look at the [MDN article for display](https://developer.mozilla.org/en-US/docs/Web/CSS/display), it appears that `display: run-in` was experimental and now being finalized in CSS 3.

Hence, consider moving to CSS3 tests?

**Comment by dauwhe** [comment]
Well, it was in CSS 2, so it's been around for a while. It's not in 2.1, so probably appropriate to move?

**Comment by gsnedders** [comment]
Where do we have `display: run-in` tests still in 2.1? I thought they'd all been moved to css-box-3? `grep -R run-in css21` finds nothing.

**Comment by hrj** [comment]
Yeah, in this repo they are under css-box-3 folder, but they also end up inside the nightly build published here: https://test.csswg.org/suites/css21_dev/

```
wget https://test.csswg.org/suites/css21_dev/nightly-unstable.zip
unzip -l nightly-unstable.zip | grep run-in | wc -l
```

Output is: 423

**Comment by dbaron** [comment]
Presumably the &lt;link rel="help"&gt;s need to be pointed to css-box-3 instead of CSS21.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5494; please continue all discussion there.
