### ISSUE TITLE
Some tests are missing in xhtml1/reftest-toc.xht

### ISSUE THREAD

**Issue by hrj** [w3c/csswg-test#1138]
I can't find `position-applies-to-008.xht` in the xhtml1 and html4 TOC.

I guess that's probably because `<link rel="match" href="..." />` is missing in the file. Is that correct?

There are couple of others such as `top-applies-to-008.xht`, etc.

**Comment by plinss** [comment]
Correct, if a test doesn't have a "match" or "mismatch" link then the build system won't see it as a reference test (because it doesn't know what the reference files are) and it wont get included in the reftest manifest.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5496; please continue all discussion there.
