### ISSUE TITLE
Travis CI is broken again

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-test#1140]
https://travis-ci.org/w3c/csswg-test/builds/171878768 is timing out. (I restarted it to try and understand if it was doing something super-weird. It is.)

It seems to be building far, far more commits than it should be building. It should be building:

```
$ git log --pretty=%H -r e9939f9ba7ada29cc83ce15f64cb0b7327a008d5..108065d16ccb67a00c9bc197a54d105933b97288
108065d16ccb67a00c9bc197a54d105933b97288
179747bd001e52338b6838374adc6fbd4fe80586
```

In actuality, it's starting off building dc546342df5a876c3efd193edd3b16a65f538dbc, a commit from 2015, an ancestor of e9939f9ba7ada29cc83ce15f64cb0b7327a008d5. I'm very confused by this. I have no idea what's happening.

/cc @frivoal (as it's your commit that's erroring), @jgraham (as the "maintainer" of css-test-built), @Ms2ger (as the guy who seems to care most about css-test-built in the one place it is used: Servo)

One option is to just kill css-test-built and never have to debug this hell ever again. Another is to convince someone it's worth their time and money to have Travis CI builds passing.

**Comment by gsnedders** [comment]
There's a part of me that wonders if this is simply a bug in `git-log`, in the ancient version on Travis?

**Comment by gsnedders** [comment]
I've now run the script locally and css-test-built is back up to date relative to when I started the script, and I've rerun the Travis build that is current the HEAD of master, which is now building a mere five revisions and hence should actually complete. Obviously relying on me to run it locally whenever it breaks doesn't scale!

**Comment by Ms2ger** [comment]
Agreed, but I hope it won't happen again between now and the merge into wpt

**Comment by gsnedders** [comment]
For when this next happens:

```
$ git clone --reference csswg-test git@github.com:w3c/csswg-test.git csswg-test-again
$ cd csswg-test-again
$ export TRAVIS_COMMIT=`git log -n1 --pretty=%H`
$ python tools/travis/build.py
$ cd tools/travis/css-test-built
$ git remote add origin-ssh git@github.com:jgraham/css-test-built.git
$ git push origin-ssh
```
```

**Comment by gsnedders** [comment]
So, I'm pretty certain it's an ancient version of git bug. Will file PR once I've locally rebuilt css-test-built to move Travis to Trusty.
