### ISSUE TITLE
Add tests for `new DOMMatrix('none')`

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-test#1173]
See https://github.com/w3c/fxtf-drafts/issues/55

Variants to test: leading/trailing whitespace, uppercase, CSS comments before/after. (should all work I think)

Also: empty string (should work), and only whitespace (should throw).

https://github.com/w3c/csswg-test/blob/master/geometry-1/DOMMatrix-001.html

cc @tim-loh

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5497; please continue all discussion there.
