### ISSUE TITLE
Test suite build breaks a caret-color test

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-test#1181]
https://test.csswg.org/suites/css-ui-3_dev/nightly-unstable/html/caret-color-015.htm

This test needs an already visited link to be valid, so asks the tester to visit the url of the test itself and try again. However, the build system changes the name of the test from caret-color-015.html to caret-color-015.htm (without the **l** in the file extension), so the file you're supposed to visit doesn't exist.

Should we fix this by:
* pointing to the post-build url? I don't like this, as it makes the unbuild test wrong
* pointing to some other url? Ok, but what? www.w3.org?
* Fixing the build system to not change the file names?
* something else? 

CC: @plinss @gsnedders

**Comment by frivoal** [comment]
Same problem with this one: https://test.csswg.org/harness/test/css-ui-3_dev/spec/css-ui-3/section/6.2.1/caret-color-016/

**Comment by mrego** [comment]
I've found this test: https://github.com/w3c/csswg-test/blob/master/css21/selectors/link-visited-selector-004.xht
The name of the test is `link-visited-selector-004.xht` but the link points to `link-visited-selector-004.htm`, maybe we could follow a similar approach.

**Comment by frivoal** [comment]
I don't like the fact that the test does not work if the test suite is not built, when you do that.

I'll just replace with a link to w3.org

**Comment by frivoal** [comment]
@mrego Actually, I've tried something else. Can you please review #1183 ?

**Comment by mrego** [comment]
@frivoal actually I'm fine with any of those options.
But it'd be nice to hear the feedback from other people about this topic, just in case they've different suggestions.

**Comment by gsnedders** [comment]
We have loads of bugs like this all over the testsuite. Nobody has ever come up with any way to fix them, and a proper fix requires changes to the build system, and I don't think anyone is volunteering to change the build system.

Notably, we can't:

 * point to the post-build URL, because we don't know what that is (is it `foo.html` or `foo.xht`? it depends which format we've built to),
* rely on any external page (because CI systems block network access for the sake of reproducibility).

**Comment by frivoal** [comment]
In that case, I think what I suggested in #1183 is a good way to go. Probably does not work in the general case, but for our purpose it should. @mrego, any comment before we merge it?

**Comment by gsnedders** [comment]
IMO we should make sure we have the right URL for the unbuilt test suite everywhere, given the build system will be dying.

**Comment by frivoal** [comment]
Hopefully that happens soon, but that's still in the future, and for now, it break the test on test https://test.csswg.org/harness/ . I'd rather not have broken tests and unusable test suites.

How far away are we from having https://test.csswg.org/harness/ serve unbuilt tests?

**Comment by mrego** [comment]
Note that browsers differ here, in a file called "foobar.html", if you've a link to "foobar.html" is not considered visited on the first load in Blink.
However if you have `href=""` it is.

I don't know if these are interop issues, or just that the spec doesn't define this specific behavior.
