### ISSUE TITLE
Build process misses support files for css-values-3_dev/html/vh_not_refreshing_on_chrome.htm

### ISSUE THREAD

**Issue by jdm** [w3c/csswg-test#1200]
The [reference file](https://github.com/w3c/csswg-test/blob/master/css-values-3/reference/vh_not_refreshing_on_chrome-ref.html) for this test uses an iframe that loads [this file](https://github.com/w3c/csswg-test/blob/master/css-values-3/reference/vh_not_refreshing_on_chrome_iframe-ref.html), but it is missing from the repo containing the compiled tests: https://github.com/jgraham/css-test-built/tree/master/css-values-3_dev/html/reference.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5499; please continue all discussion there.
