### ISSUE TITLE
css-values-3_dev/html/vh_not_refreshing_on_chrome.htm has multiple problems

### ISSUE THREAD

**Issue by jdm** [w3c/csswg-test#1201]
1. the test file (and the [reference](https://github.com/w3c/csswg-test/blob/master/css-values-3/reference/vh_not_refreshing_on_chrome-ref.html)) both modify the height of the iframe from repeated setTimeout callbacks until the a maximum height is reached, but there's no use of `reftest-wait` to prevent a screenshot from being being taken too early.
2. the [page](vh_not_refreshing_on_chrome_iframe.html
) loaded in the iframe has a `<link rel="match">` duplicated from the parent page which does not belong.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5500; please continue all discussion there.
