### ISSUE TITLE
clip-path-square-001-ref.svg and clip-path-square-002-ref.svg get lost by the build system

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-test#1236]
This is caused by the duplicated filename between `css-masking-1/clip-path-svg-content/reference/clip-path-square-001-ref.svg` and `css-masking-1/clip-path/reference/clip-path-square-001-ref.html` (and similarly for 002), but the build system doesn't notice this and doesn't give a warning for it.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5503; please continue all discussion there.
