### ISSUE TITLE
Directories whose name are not shortnames

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-test#1246]
When we merge into web-platform-tests (#1102), because it is an inherently breaking move, we should make sure all the shortnames match up.

Those that don't are:

 * WOFF2-UserAgent (should be WOFF2)
 * css-logical-properties-1 (we have it as css-logical-props on drafts.csswg.org, but yet to have a FPWD so doesn't have a formal shortname)
 * css-round-display (should be css-round-display-1)
 * css-style-attr-1 (should be css-style-attr; spec has no stated version, is a REC and presumably not changing?)
 * css-transitions-2 (yet to have FPWD so doesn't have a formal shortname)
 * css-values-4 (yet to have FPWD so doesn't have a formal shortname)
 * css1 (should be REC-CSS1; is a REC and presumably not changing?)
 * css21 (should be CSS2; is a REC and presumably not changing?)
 * filters-1 (should be filter-effects-1)
 * selectors-4 (should be selectors4, or are we changing it?)

There is also:

 * css-backgrounds-3 (should be css3-background, or are we changing the shortname?)
 * css-box-3 (should be css3-box; ditto unless otherwise stated)
 * css-color-3 (should be css3-color; is a REC and presumably not changing?)
 * css-images-3 (should be css3-images)
 * css-page-3 (should be css3-page)
 * mediaqueries-3 (should be css3-mediaqueries)
 * selectors-3 (should be css3-selectors; is a REC and presumably not changing?)

And the following that have been renamed to Level 1:

 * css-animations-1 (last published as css3-animations, though since renamed to level 1, so I presume that will be its shortname in future?)
 * css-exclusions-1 (last published as css3-exclusions; ditto unless otherwise stated)
 * css-multicol-1 (last published as css3-multicol)
 * css-speech-1 (last published as css3-speech)
 * css-transitions-1 (last published as css3-transitions)

cc/ @astearns @jgraham @tobie

**Comment by fantasai** [comment]
Comments on your comments:

- Unsure about css-logical-props. Should have a level of course, but unclear about the shortname as yet
- css1 is css1, not REC-CSS1.
- no opinion on selectors4, we could change it if people prefer the hyphen
- css3-box is likely to end up as css-block-3
- RECs are unlikely to change, agreed

Otherwise looks good.

**Comment by gsnedders** [comment]
Okay, so the plan is:

 * WOFF2-UserAgent -> woff2 (everything else is lowercase, so let's just stick with that)
 * css-round-display -> css-round-display-1
 * css-style-attr-1 -> css-style-attr
 * css21 -> css2
 * filters-1 -> filter-effects-1
 * selectors-4 -> selectors4
 * css-box-3 -> css-block-3
 * css-color-3 -> css3-color
 * selectors-3 -> css3-selectors

And everything else stays as-is.

**Comment by tobie** [comment]
Fwiw, I'd rather your stick with whatever casing the short names are using, even if those are inconsistent (or get those inconsistencies fixed at the tr.rdf level).

**Comment by gsnedders** [comment]
Okay, then we have:

 * WOFF2-UserAgent -> WOFF2
 * css21 -> CSS2
 * css1 -> CSS1 (REC-CSS1 is apparently a bug in tr.rdf, given what the spec says itself inline)

**Comment by tobie** [comment]
Think I fix rhe REC prefix in Specref.

**Comment by gsnedders** [comment]
That's now fixed in tr.rdf according to email, though I've not verified.

**Comment by gsnedders** [comment]
Yeah, that's now fixed.

**Comment by gsnedders** [comment]
Now done as part of the merge.

The full move:

```
git mv WOFF2-UserAgent/Tests/xhtml1 WOFF2
git mv WOFF2-UserAgent/OWNERS WOFF2
git mv css-round-display css-round-display-1
git mv css-style-attr-1 css-style-attr
git mv css1 CSS1
git mv css21 CSS2
git mv filters-1 filter-effects-1
git mv selectors-4 selectors4
git mv css-box-3 css-block-3
git mv css-color-3 css3-color
git mv selectors-3 css3-selectors
```

This is <https://github.com/w3c/web-platform-tests/commit/3f336bad52bd7395a5e9cb4addbbfc8a2770011c>.
