### ISSUE TITLE
shape-outside none

### ISSUE THREAD

**Issue by rhauck** [w3c/csswg-test#129]
_Issue by **[lmclister](https://github.com/lmclister)** from Wednesday Oct 02, 2013 at 22:52 GMT_
_Originally opened as https://github.com/adobe-webplatform/csswg-test/issues/62_

---

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5426; please continue all discussion there.
