### ISSUE TITLE
box-sizing

### ISSUE THREAD

**Issue by lastorset** [w3c/csswg-test#217]
The 'padding-box' value is at risk, so testing it is especially interesting, but all values should be tested; they can probably all be tested with the same approach. An approach to testing could be to make boxes whose borders line up if the browser implements the property correctly.

**Comment by frivoal** [comment]
This commit gives a good coverage of the box-sizing property: https://github.com/w3c/csswg-test/commit/77540234def595448ef5266a4695e1a7a1c1f89e If we need more, we should be more specific about what needs to be tested.
