### ISSUE TITLE
Outline properties

### ISSUE THREAD

**Issue by lastorset** [w3c/csswg-test#218]
There are differing interpretations of outlines accross browsers. For instance, are outlines drawn on top of everything in the document, or just everything in an element's box? Other things to test could be
- that the outline doesn't influence the position or size of the box or any other boxes
- that the outlines are unbroken and non-rectangular when appropriate
- that the 'auto' value produces an outline (though with arbitrary rendering)
- that all values of 'border-style' are accepted as 'outline-style'

**Comment by frivoal** [comment]
Addressed by #1192
