### ISSUE TITLE
Simple <div>

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#219]
## Test case description

1 element required: [B] 
[B] - element with mix-blend-mode other than normal

For details about the notations and more in-context information please refer to section **An element with mix-blend-mode other than normal creates a stacking context** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The element [B] creates a stacking context
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
