### ISSUE TITLE
Blending <video>

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#221]
## Test case description

2 elements required: [B] and [IN-S] 
[B] - <video> element with mix-blend-mode other than normal 
[IN-S] - sibling(of the element [B]) visually overlaping the <video> element 
[IN-S] has some text inside

For details about the notations and more in-context information please refer to section **An element with mix-blend-mode blends with the content within the current stacking context** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The content of the video element [B] mixes with the colors of the sibling element and the text from [IN-S].
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
