### ISSUE TITLE
Parent with transparent pixels

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#225]
## Test case description

2 elements required: [P] and [B] 
[P] - parent element with a property that creates a stacking context (e.g. position:fixed) 
The element has some text inside and default value for background-color 
[B] - element with mix-blend-mode other than normal 
The background-color of the body has a value other than default

For details about the notations and more in-context information please refer to section **An element with mix-blend-mode doesn't blend with anything outside the current stacking context** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The color of the text from the parent element [P] mixes with the color of the child element [B]. 
No blending between the color of the body and the color of the blending element [B].
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
