### ISSUE TITLE
Parent with border-radius

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#226]
## Test case description

2 elements required: [P] and [B] 
[P] - parent element with a property that creates a stacking context (e.g. position:fixed) 
[P] has border-radius specified (e.g.50%). 
[B] - element with mix-blend-mode other than normal 
[B] has content that lies outside the parent element, over a rounded corner. 
The background-color of the body has a value other than default. 

For details about the notations and more in-context information please refer to section **An element with mix-blend-mode doesn't blend with anything outside the current stacking context** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The color of the parent element mixes with the color of the child element. 
 The area of the child element which draws over the rounded corner doesn't mix with the color of the body
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
