### ISSUE TITLE
Overflowed child of the blended element

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#228]
## Test case description

3 elements required: [P], [B] and [CB] 
[P] - parent element with a property that creates a stacking context (e.g. position:fixed) 
[B] - element with mix-blend-mode other than normal 
[CB] - child of the element [B] with content that lies outside the parent element [B].

For details about the notations and more in-context information please refer to section **An element with mix-blend-mode other than normal must cause a group to be isolated** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The group created by the two child elements([B] and [CB]) is blended with the parent element [P]. 
No blending between [B] and [CB]. There is only one color for the entire element [CB] 
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
