### ISSUE TITLE
Blended element with transform and preserve-3d

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#233]
## Test case description

3 elements required: [P], [B] and [CB] 
[P] - parent element with a property that creates a stacking context (e.g. position:fixed) 
[B] - element with mix-blend-mode other than normal and transform with transform-style:preserve-3d 
[CB] - child of the element [B]. It has 3D transform property

For details about the notations and more in-context information please refer to section **An element with mix-blend-mode must work properly with css transforms** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

 The child element [CB] will NOT preserve its 3D position. 
mix-blend-mode override the behavior of transform-style:preserve-3d:
creates a flattened representation of the descendant elements 
The color of the group created by the child elements([B] and [CB]) will blend with the color of the parent element [P] 
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
