### ISSUE TITLE
Sibling with 3D transform between the parent and the blended element

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#235]
## Test case description

3 elements required: [P], [B] and [IN-S] 
[P] - parent element with a property that creates a stacking context (e.g. position:fixed) 
[B] - element with mix-blend-mode other than normal 
[IN-S] - Sibling(of the element [B]) with 3D transform between the parent [P] and the child [B]

For details about the notations and more in-context information please refer to section **An element with mix-blend-mode must work properly with css transforms** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The colors of the parent element [P] and the transformed sibling element [IN-S] mixes with the color of the blended element [B].
The element (and the content) of the element [IN-S] is properly transformed
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
