### ISSUE TITLE
Parent with 3D transform and transition

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#236]
## Test case description

2 elements required: [P] and [B] 
[P] - parent element with 3D transform and transition 
[B] - element with mix-blend-mode other than normal
The color of the parent element [P] mixes with the color of the child element [B] 
The element (and the content) of the element [P] is properly transformed

For details about the notations and more in-context information please refer to section **An element with mix-blend-mode must work properly with css transforms** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The color of the parent element [P] mixes with the color of the child element [B] 
The element (and the content) of the element [P] is properly transformed
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
