### ISSUE TITLE
Parent element with overflow:scroll

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#238]
## Test case description

2 elements required: [P] and [B] 
[P] - parent element with a property that creates a stacking context (e.g. position:fixed) 
[P] has overflow:scroll 
[B] - element with mix-blend-mode other than normal tat overflows the parents [P] dimensions so that it creates scrolling for the parent
The color of the parent element [P] mixes with the color of the child element [B]. 
The scrolling mechanism is not affected.

For details about the notations and more in-context information please refer to section **An element with mix-blend-mode must work properly with elements with overflow property** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The color of the parent element [P] mixes with the color of the child element [B]. 
The scrolling mechanism is not affected.
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
