### ISSUE TITLE
Intermediate child with overflow:hidden and border-radius between the parent and the blended element

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#243]
## Test case description

3 elements required: [P], [B] and [IN-P] 
[P] - parent element with a property that creates a stacking context (e.g. position:fixed) 
[B] - element with mix-blend-mode other than normal that overflows the parents [IN-P] dimensions
[IN-P] - child(of the element [P]) with overflow:hidden and border-radius specified (e.g.50%)

For details about the notations and more in-context information please refer to section **An element with mix-blend-mode must work properly with elements with overflow property** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The colors of the parent element [P] and the child element [IN-P] mixes with the color of the blended element [B]. 
[B] is is properly clipped so no overflow is visible
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
