### ISSUE TITLE
Blended element with border-image

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#244]
## Test case description

2 elements required: [P] and [B] 
[P] - parent element with a property that creates a stacking context (e.g. position:fixed) 
[B] - element with mix-blend-mode other than normal and border-image specified as a png file

For details about the notations and more in-context information please refer to section **Other test cases** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The color of the parent element [P] mixes with the color of the child element. 
The color of the border-image mixes with the color of the parent element [P].
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
