### ISSUE TITLE
Blending with <canvas>

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#245]
## Test case description

2 elements required: [B] and [IN-S] 
[B] - <canvas> element with mix-blend-mode other than normal 
[IN-S] - Sibling of the <canvas> element with some text 
The [IN-S] element overlaps the <canvas> element

For details about the notations and more in-context information please refer to section **Other test cases** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The content of the <canvas> element mixes with the color of the sibling element and the text [IN-S].
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
