### ISSUE TITLE
Blended element with mask property

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#250]
## Test case description

2 elements required: [P] and [B] 
[P] - parent element with a property that creates a stacking context (e.g. position:fixed) 
[B] - element with mix-blend-mode other than normal and mask property specified to an SVG image (e.g. circle)

For details about the notations and more in-context information please refer to section **Other test cases** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The colors of the parent and the masked child are mixed ([P] and [B])
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
