### ISSUE TITLE
Circle with SVG background

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#262]
## Test case description

Set a background color for the SVG.
Create 16 circle elements and fill them with a solid color.
Apply each mix-blend-mode on them.

For details about the notations and more in-context information please refer to section **mix-blend-mode with simple SVG graphical elements** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The color of the circle is mixed with the color of the background.
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
