### ISSUE TITLE
Blending in a group with 3D transform

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#283]
## Test case description

Set a background color for the SVG.
Create a group element containing a rect element filled with a different solid color.
Apply a 3d transform on the group and a mix-blend-mode other than normal on the rect.

For details about the notations and more in-context information please refer to section **mix-blend-mode with isolated groups** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The rect will not mix with the content behind it.
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
