### ISSUE TITLE
Blend with SVG having viewbox and preserveAspectRatio set

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#291]
## Test case description

Set a background color for the SVG, as well as viewbox and preserveAspectRatio.
Create a rect element filled with a different solid color and apply a mix-blend-mode other than normal on it.

For details about the notations and more in-context information please refer to section **Other test cases for SVG** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The rect will mix with the content behind it.
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
