### ISSUE TITLE
Blending two elements in an isolated group - SVG isolation:isolate

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#299]
## Test case description

Set a background color for the SVG.
Create a group element containing two overlapping rect elements, each filled with a different solid color.
Apply isolation:isolate on the group and a mix-blend-mode other than normal on the second rect.

For details about the notations and more in-context information please refer to section **In SVG, an element with isolation:isolate creates an isolated group for blended children** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

Only the intersection of the rect elements should mix.
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
