### ISSUE TITLE
Isolate inside a stacking context created by a 3d transform

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#300]
## Test case description

3 elements required: [P], [IN-P] and [B] 
[P] - parent element with a 3D transform applied
[IN-P] - Intermediate child element between the parent [P] and the child [B]
The intermediate element has isolation:isolate set
[B] - element with mix-blend-mode other than normal

For details about the notations and more in-context information please refer to section **An element with isolation:isolate creates an isolated group for blended children** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The color of the child element [B] mixes with the color of the intermediate element [IN-P], where they overlap.
There is no blending between the color of the parent element [P] and the color of the blended element [B].
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
