### ISSUE TITLE
Gradient and background color

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#302]
## Test case description

Element with

background-image set to an <gradient>
background-color set to a fully opaque color
background-blend-mode other than normal

For details about the notations and more in-context information please refer to section *_Blending between the background layers and the background color for an element with background-blend-mode *_ of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The content of the background-image is mixed with the color of the background-color
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
