### ISSUE TITLE
Image and gradient

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#303]
## Test case description

Element with

background-image set to an <image> on top of a <gradient>
background-blend-mode other than normal

For details about the notations and more in-context information please refer to section *_Blending between the background layers and the background color for an element with background-blend-mode *_ of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The content of the <image> is mixed with the content of the <gradient>
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
