### ISSUE TITLE
One background layer

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#308]
## Test case description

Element with

background-image set to an <image>
background-blend-mode other than normal

For details about the notations and more in-context information please refer to section **Background layers do not blend with content outside the background (or behind the element)** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The background-image is not mixed with anything outside the element
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
