### ISSUE TITLE
Two elements

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#309]
## Test case description

2 elements required: a parent element with a child. 
Each one with the following properties:

background-color set to a fully opaque color
background-blend-mode other than normal

No blending between the background colors of the two elements

For details about the notations and more in-context information please refer to section **Background layers do not blend with content outside the background (or behind the element)** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

No blending between the background colors of the two elements
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
