### ISSUE TITLE
Different blend modes applied between layers

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#310]
## Test case description

Element with

background-image set to an <image-list> containing three images: (e.g. I1, I2 and I3 ) 
background-blend-mode set to different blendmode for every image: (e.g. multiply, difference, screen) 

For details about the notations and more in-context information please refer to section *\* background-blend-mode list values apply to the corresponding background layer*\* of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The content of the three images is correctly mixed 
(multiply for I1, difference for I2 and screen for I3)
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
