### ISSUE TITLE
Blend mode list repeat

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#311]
## Test case description

Element with

background-image set to an <image-list> containing three images
background-blend-mode set to two different blendmode values

For details about the notations and more in-context information please refer to section **background-blend-mode list values are repeated if the list is shorter than the background layer list** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The unspecified blend modes should be obtained by repeating the blend mode list from the beginning
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
