### ISSUE TITLE
Default blend mode for 'background' shorthand

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#312]
## Test case description

Element with

background property set to an image and a color
No value explicitly set for background-blend-mode 

For details about the notations and more in-context information please refer to section *_The default background-blend-mode value for the background shorthand is 'normal' *_ of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

 The computed value of background-blend-mode is 'normal'
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
