### ISSUE TITLE
Background size cover

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#316]
## Test case description

Element with

background-image set to an <image>
background-color set to a fully opaque color
background-size set to cover
background-blend-mode other than normal

For details about the notations and more in-context information please refer to section **background-blend-mode for an element with background-size** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The content of the background-image is mixed with the color of the background-color 
The background-image has the correct size
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
