### ISSUE TITLE
box-sizing tests accidentally pass

### ISSUE THREAD

**Issue by lastorset** [w3c/csswg-test#370]
Oops: one of the tests I approved in https://github.com/w3c/csswg-test/pull/329/ will accidentally pass if the property is not supported. If they implement the correct box model, UAs will accidentally pass the content-box test; if they're compatible with old IE, they'll pass the border-box test.

I think one correct approach would be to include the code from another test in each test file (for example copy the border-box test into the content-box test) so that it passes with two green boxes.

**Comment by frivoal** [comment]
One way to fix that would be to make the test and the ref test use different values of box-sizing. That way, no browser would pass it unless they actually support the property and the ability to switch between multiple box-sizing models.

**Comment by gsnedders** [comment]
Then you're relying on the property under test in the reference, which doesn't seem great. I'd just go for a 100px green square (when passing, obviously!), where the top 50px uses `border-box` and the bottom 50px uses `content-box`.

**Comment by frivoal** [comment]
This is no longer relevant, as it pertains to tests that have been removed for being duplicates of existing tests.
