### ISSUE TITLE
Isolation of blended child which overflows

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#374]
## Test case description

3 elements required:
[P],
[IN-P] and
[B] 
[P] - parent element with a property that creates a stacking context (e.g. position:fixed) 
[IN-P] - Intermediate child element between the parent [P] and the child [B]
This element has isolation:isolate set.
[B] - element with mix-blend-mode other than normal 
The blending element [B] has content that lies outside the parent element. 

For details about the notations and more in-context information please refer to section **An element with isolation:isolate creates an isolated group for blended children** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The color of the child element [B] mixes with the color of the intermediate element [IN-P], where they overlap.
The area of the child element outside of the intermediate parent element does not mix with the color of the parent element [P], or of the body.
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
