### ISSUE TITLE
Isolation auto

### ISSUE THREAD

**Issue by Mire** [w3c/csswg-test#375]
## Test case description

Have an element with isolation explicitly set to auto, and no other style that would create a stacking context

For details about the notations and more in-context information please refer to section **An element with isolation:auto set does not change the elements existing stacking context behavior** of the test plan:
http://mire.github.io/css-blending-test-plan-proposal/css-blending-test-plan-proposal.html
## Expected result

The element does not create a stacking context - the computed value of its z-index is value auto
## W3C specification

This test case pertains to the following w3c specification:
http://www.w3.org/TR/compositing-1/

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5555; please see that issue if you wish to discuss or work on this.
