### ISSUE TITLE
Regions' pseudo-elements

### ISSUE THREAD

**Issue by mibalan** [w3c/csswg-test#449]
Test the proper rendering and processing of the pseudo-elements of the          regions. Refers to [section 5](http://dev.w3.org/csswg/css-regions/#pseudo_elements) of         the Regions spec.

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5556; please see that issue if you wish to discuss or work on this.
