### ISSUE TITLE
Regions auto-sizing

### ISSUE THREAD

**Issue by mibalan** [w3c/csswg-test#450]
Test the auto-sizing of regions based on [section 7](http://dev.w3.org/csswg/css-regions/#regions-visual-formatting-details)            of the Regions spec. Regions with `height`/`width` set to `auto`, handling of `min-` and            `max-` `width`/`height`, proper processing of forced breaks in auto-height regions.

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5556; please see that issue if you wish to discuss or work on this.
