### ISSUE TITLE
DOM additions - `offsetTop`, `offsetBottom`, `offsetLeft`, `offsetRight` and `offsetParent`

### ISSUE THREAD

**Issue by mibalan** [w3c/csswg-test#456]
Test that `offsetTop`, `offsetBottom`, `offsetLeft`, `offsetRight` and `offsetParent`           work correctly with content fragmented in regions.

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5556; please see that issue if you wish to discuss or work on this.
