### ISSUE TITLE
CSS Regions and CSS3 Sizing additions

### ISSUE THREAD

**Issue by mibalan** [w3c/csswg-test#459]
[CSS3 Sizing](http://www.w3.org/TR/css3-sizing/) introduces new keywords            and behaviors for `width`/`height` and co. Test that auto-sized regions respect the         semantic of the new keywords.

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5556; please see that issue if you wish to discuss or work on this.
