### ISSUE TITLE
CSS Regions and fragmentation

### ISSUE THREAD

**Issue by mibalan** [w3c/csswg-test#470]
Fragmentation of different types of content through CSS Regions (should         also include ("pathological") edge-cases, parallel flows, etc.) and fragmentation of            CSS Regions inside different fragmentation contexts (regions, multicol, page).

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5556; please see that issue if you wish to discuss or work on this.
