### ISSUE TITLE
Writing Modes: text-combine-upright values

### ISSUE THREAD

**Issue by myakura** [w3c/csswg-test#568]
fairly basic test cases for `text-combine-upright` using Ahem.

* tests should match `<span.ahem>x</span>`
  * `<span.tcu-all.ahem>AAA</span>`
  * `<span.tcu-digits2.ahem>` + 2 digits
  * `<span.tcu-digits3.ahem>` + 2 digit and 3 digits
  * `<span.tcu-digits4.ahem>` + 3 digit and 4 digits
* tests should match `<span.ahem>xxx</span>`
  * `<span.tcu-none.ahem>AAA</span>`
  * `<span.tcu-digits2.ahem>` + 3 digits
* tests should match `<span.ahem>xxxx</span>`
  * `<span.tcu-digits3>` + 4 digits
* tests should match `<span.ahem>xxxxx</span>`
  * `<span.tcu-digits4>` + 5 digits

Plus,

* `<span.tcu-digits2>` + 1 digit and its reference
  * it cannot use Ahem as it only contains a single character
  * does `<span.tcu-digits2>1</span>` match `<span.to-upright>1</span>` ?
    * may be okay for this case (ascii digit)... not sure if it's workable on .tcu-all + A for instance...

**Comment by myakura** [comment]
TCY of single character cases are being addressed in #747

**Comment by kojiishi** [comment]
I suppose this issue is dead now and I'm closing. Please feel free to re-open if this is still active.
