### ISSUE TITLE
Writing Modes: text-combine-upright look-ahead/look-behind sequencing rules

### ISSUE THREAD

**Issue by myakura** [w3c/csswg-test#570]
[9.1.1 Text Run Rules](http://dev.w3.org/csswg/css-writing-modes/#text-combine-runs) defines that UA must look at the characters appear before and after the run for not combining part of the sequence.

The section comes with an example where `text-combine-upright` doesn't combine any of the character in `<tcy>12<span>34</span></tcy>` but does for "34" in `12<tcy><span></span>34</tcy>`.

I think tests should borrow these; I'd go with `12<tcy><span></span>3</tcy>` rather than `34` to make it reftestable. This also makes the test not depending on compression processing.

This yeilds following combinations:

* `<span class="tcy"><span>12</span>3</span>`
* `<span class="tcy">1<span>23</span></span>`
* `<span class="tcy"><span>1</span></span>23`
* `12<span class="tcy"><span>3</span></span>`

where `.tcy` have `text-combine-upright: all` and `text-combine-upright: digits 4`; hence, eight tests.

**Comment by kojiishi** [comment]
I suppose this issue is dead now and I'm closing. Please feel free to re-open if this is still active.
