### ISSUE TITLE
[css-grid] Static position of grid container children

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-test#642]
The static position of an absolutely-positioned child of a grid container is determined as if it were the sole grid item in a fixed-size grid area whose edges coincide with the padding edges of the grid container.
More info: http://www.w3.org/TR/css-grid-1/#static-position

Note that if the grid container generates an absolutely positioned containing block, then we should apply the rules at [8.4 Absolutely-positioned Grid Items](http://www.w3.org/TR/css-grid-1/#static-position) section.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5433; please continue all discussion there.
