### ISSUE TITLE
[css-grid] Implicit named areas

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-test#651]
Since a named grid area is referenced by the implicit named lines it produces, explicitly adding named lines of the same form (`foo-start`/`foo-end`) effectively creates a named grid area.
More info: http://www.w3.org/TR/css-grid-1/#implicit-named-areas

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5437; please continue all discussion there.
