### ISSUE TITLE
[css-grid] 'grid-template' property

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-test#652]
The `grid-template` property is a shorthand for setting `grid-template-columns`, `grid-template-rows`, and `grid-template-areas` in a single declaration.
http://www.w3.org/TR/css-grid-1/#explicit-grid-shorthand

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5438; please continue all discussion there.
