### ISSUE TITLE
[css-grid] 'grid-auto-rows' and 'grid-auto-columns' properties

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-test#662]
If a grid item is positioned into a row or column that is not explicitly sized by `grid-template-rows` or `grid-template-columns`, implicit grid tracks are created to hold it. This can happen either by explicitly positioning into a row or column that is out of range, or by the auto-placement algorithm creating additional rows or columns. The `grid-auto-columns` and `grid-auto-rows` properties specify the size of such implicitly-created tracks.
More info: http://www.w3.org/TR/css-grid-1/#auto-tracks

**Comment by mrego** [comment]
We need more tests yet, so reopening it.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5439; please continue all discussion there.
