### ISSUE TITLE
[css-grid] 'grid-auto-flow' property

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-test#663]
Grid items that aren’t explicitly placed are automatically placed into an unoccupied space in the grid container. The 'grid-auto-flow' property controls the direction in which the search for unoccupied space takes place, and whether rows or columns are added as needed to accommodate the content.
More info: http://www.w3.org/TR/css-grid-1/#grid-auto-flow-property

_Note: The definitive values for this property are still under discussion in the CSS WG._

**Comment by mrego** [comment]
It seems that the values for this property are definite now: `[ row | column ] || dense`

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5440; please continue all discussion there.
