### ISSUE TITLE
[css-grid] Named areas placement

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-test#665]
An item can be placed into a named grid area (such as those produced by the template in `grid-template-areas`) by specifying the area’s name in `grid-area`.
An item can also be partially aligned with a named grid area, with other edges aligned to some other line.
More info: http://www.w3.org/TR/css-grid-1/#common-uses-named-areas

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5442; please continue all discussion there.
