### ISSUE TITLE
[css-grid] Numeric indexes and spans placement

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-test#666]
Grid items can be positioned and sized by number, which is particularly helpful for script-driven layouts.
By default, a grid item has a span of 1. Different spans can be given explicitly.
More info: http://www.w3.org/TR/css-grid-1/#common-uses-numeric

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5443; please continue all discussion there.
