### ISSUE TITLE
[css-grid] Auto placement

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-test#668]
A grid item can be automatically placed into the next available empty grid cell, growing the grid if there’s no space left.
Auto-placement can be combined with an explicit span, if the item should take up more than one cell.
More info: http://www.w3.org/TR/css-grid-1/#common-uses-auto-placement

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5445; please continue all discussion there.
