### ISSUE TITLE
[css-grid] 'grid-row-start', 'grid-column-start', 'grid-row-end', and 'grid-column-end' properties

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-test#669]
The `grid-row-start`, `grid-column-start`, `grid-row-end`, and `grid-column-end` properties determine a grid item’s size and location within the grid by contributing a line, a span, or nothing (automatic) to its grid placement, thereby specifying the inline-start, block-start, inline-end, and block-end edges of its grid area.
More info: http://www.w3.org/TR/css-grid-1/#line-placement

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5446; please continue all discussion there.
