### ISSUE TITLE
[css-grid] 'grid-column', 'grid-row', and 'grid-area' properties

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-test#671]
The `grid-row` and `grid-column` properties are shorthands for `grid-row-start`/`grid-row-end` and `grid-column-start`/`grid-column-end`, respectively.
`grid-area` property is a shorthand for both `grid-row-start`/`grid-row-end` and `grid-column-start`/`grid-column-end`.
More info: http://www.w3.org/TR/css-grid-1/#placement-shorthands

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5448; please continue all discussion there.
