### ISSUE TITLE
[css-grid] Absolutely-positioned grid items

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-test#672]
If an absolutely positioned element’s containing block is generated by a grid container, its containing block edges are the edges of the element’s grid area as given by its grid-placement properties.
More info: http://www.w3.org/TR/css-grid-1/#abspos-items

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5449; please continue all discussion there.
