### ISSUE TITLE
[css-grid] 'justify-self' and 'justify-items' properties

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-test#674]
Grid items can be aligned in the inline dimension by using the `justify-self` property on the grid item or `justify-items` property on the grid container, as defined in [CSS3-ALIGN](http://www.w3.org/TR/2013/WD-css3-align-20130514/).
More info: http://www.w3.org/TR/css-grid-1/#row-align

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5451; please continue all discussion there.
