### ISSUE TITLE
[css-grid] 'align-self' and 'align-items' properties

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-test#675]
Grid items can also be aligned in the block dimension by using the `align-self` property on the grid item or `align-items` property on the grid container, as defined in [CSS3-ALIGN](http://www.w3.org/TR/2013/WD-css3-align-20130514/).
More info: http://www.w3.org/TR/css-grid-1/#column-align

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5452; please continue all discussion there.
