### ISSUE TITLE
Writing Modes: text-combine-upright uses width-specific OpenType features

### ISSUE THREAD

**Issue by myakura** [w3c/csswg-test#690]
In [Compression Rules](http://dev.w3.org/csswg/css-writing-modes/#text-combine-compression) it says:

> OpenType implementations must use width-specific variants (OpenType features hwid/twid/qwid; other glyph-width features such as fwid or pwid are not included) to compress text in cases where those variants are available for all characters in the composition.

So UA with OpenType implementation don't render composition using fwid or pwid glyphs.

Later in the section it says:

> For example, a simple OpenType-based implementation might compress the text as follows:
> 
> 1. Enable 1/n-width glyphs for combined text of n characters (i.e. use OpenType hwid for 2 characters, twid for 3 characters, etc.) if the number of characters > 1. Note that the number of characters ≠ number of Unicode codepoints!
> 2. If the result is wider than 1em, horizontally scale the result to 1em.

While the paragraph is non-normative, we might want to differentiate hwid/twid/qwid glyphs.

**Comment by kojiishi** [comment]
I suppose this issue is dead now and I'm closing. Please feel free to re-open if this is still active.
