### ISSUE TITLE
Writing Modes: text-combine-upright converts fullwidth characters to non-fullwidth ones

### ISSUE THREAD

**Issue by myakura** [w3c/csswg-test#691]
In [Full-width Characters](http://dev.w3.org/csswg/css-writing-modes/#text-combine-fullwidth) the spec says:

> In order to preserve typographic color when compressing the text to 1em, when the combined text consists of more than one character, then any full-width characters must first be converted to their non-full-width equivalents by reversing the algorithm defined for text-transform: full-width in [CSS3TEXT] before applying other compression techniques.

I submitted simple test cases for fullwidth numericals [1](https://github.com/w3c/csswg-test/blob/master/css-writing-modes-3/text-combine-upright/full-width-001.html); however, I've missed doing that for non-fullwidth-numeric characters. This issue will cover that.

-----

algorithm for `text-transform: full-width`:

> The definition of fullwidth and halfwidth forms can be found on the Unicode consortium web site at [UAX11]. The mapping to fullwidth form is defined by taking code points with the <wide> or the <narrow> tag in their Decomposition_Mapping in [UAX44]. For the <narrow> tag, the mapping is from the code point to the decomposition (minus <narrow> tag), and for the <wide> tag, the mapping is from the decomposition (minus the <wide> tag) back to the original code point.
http://dev.w3.org/csswg/css-text-3/#valdef-text-transform-full-width

and links to two UAX reports:

- http://www.unicode.org/reports/tr11/
- http://www.unicode.org/reports/tr44/

**Comment by kojiishi** [comment]
I suppose this issue is dead now and I'm closing. Please feel free to re-open if this is still active.
