### ISSUE TITLE
Writing Modes: text-emphasis-001: font URL is incorrect and text-emphasis-001-notref is missing

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-test#766]
@snsk, can you check?

It would be helpful if you can check at the test harness when you approve:
http://test.csswg.org/harness/results/css-writing-modes-3_dev/grouped/section/9/

**Comment by snsk** [comment]
font path is fixed but -notref file is able to found in my cloning environment ...

**Comment by kojiishi** [comment]
@snsk, @myakura 
Could these files moved to the top directory? Files in sub-directory are moved to top when Shepherd build a test suites, and such files referencing support files is causing troublesome.
