### ISSUE TITLE
[css-regions-1] Style cascading when element is flowed in itself

### ISSUE THREAD

**Issue by mibalan** [w3c/csswg-test#78]
The CSS cascade follows the DOM order. This test(s) should make sure that in more complicated cases where an element is flowed in itself (or an indirect child gets flowed in the element) the CSS cascade does not get confused.

Something similar should cover proper CSS cascading when using nested named flows.

**Comment by csswg-test-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5424; please continue all discussion there.

**Comment by wpt-issue-mover** [comment]
This issue has been merged into https://github.com/w3c/web-platform-tests/issues/5556; please see that issue if you wish to discuss or work on this.
