### ISSUE TITLE
[css-writing-modes-3] bidi-002 has a slight offset between "C" and "D" on Trident

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-test#796]
[bidi-002](http://test.csswg.org/harness/test/css-writing-modes-3_dev/single/bidi-002/format/html5/)  has a slight offset between "C" and "D" on Trident. Is this a failure, or an issue in test?

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5461; please continue all discussion there.
