### ISSUE TITLE
declarations-009 is wrong

### ISSUE THREAD

**Issue by Ms2ger** [w3c/csswg-test#830]
Per https://bugzilla.mozilla.org/show_bug.cgi?id=1197842

**Comment by SimonSapin** [comment]
Per http://log.csswg.org/irc.w3.org/css/2015-08-25/#e581695 the change is going to be backported to CSS2, so this test should simply be updated for the new behavior.

**Comment by SimonSapin** [comment]
Per http://log.csswg.org/irc.w3.org/css/2015-08-25/#e581695 the change is going to be backported to CSS2, so this test should be updated for the new behavior.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5462; please continue all discussion there.
