### ISSUE TITLE
`'green block.png` got lost somewhere

### ISSUE THREAD

**Issue by Ms2ger** [w3c/csswg-test#832]
Which makes `uri-00{4,5}` fail.

**Comment by Ms2ger** [comment]
Likewise for `,uri-014.png`

**Comment by gsnedders** [comment]
See c1586c9c42e17cd4a243601c8885046addda183a

**Comment by gsnedders** [comment]
This appears to go all the way back to the earliest MS test dump, where there was a `'green block.png`.

**Comment by Ms2ger** [comment]
Tried reverting that commit, but the file doesn't seem to be picked up by the build system. Need to investigate further.

**Comment by gsnedders** [comment]
It needs renamed. Note the bogus names with all kinds of punctuation.

**Comment by plinss** [comment]
Note that the names with punctuation were most likely deliberate to catch parsing errors (and may contain red blocks instead of green ones).

**Comment by gsnedders** [comment]
@Ms2ger pointed this out to me on IRC.

**Comment by gsnedders** [comment]
`(green{block.png` and `,green)block.png` don't appear to be used anywhere. Or at least they don't make any tests fail anywhere?
