### ISSUE TITLE
Remove dependencies on non-free fonts

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-test#921]
See https://github.com/servo/servo/issues/8053 for the background of this. In short, a number of tests, including css21_dev/html4/font-family-013.htm and css21_dev/html4/fonts-013.htm rely on specific fonts being available, above and beyond those in http://www.w3.org/Style/CSS/Test/Fonts/.

**Comment by gsnedders** [comment]
Hmm, these don't *actually* rely on them, but it'd be better to not have this.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5464; please continue all discussion there.
