### ISSUE TITLE
[CSS22][css21] Add test for render tree cleanup bug involving float:right & display:none

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-test#923]
See:
- https://bugs.webkit.org/show_bug.cgi?id=150271
- http://code.google.com/p/chromium/issues/detail?id=544290

[The testcase from the WebKit bug](https://bugs.webkit.org/attachment.cgi?id=263749&action=edit) could be easily made into a reftest.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5466; please continue all discussion there.
