### ISSUE TITLE
Drop .htaccess for wpt-like files

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-test#925]
This drops the requirement for something Apache-like to be used, and makes us consistent with wpt. See [documentation](http://testthewebforward.org/docs/test-format-guidelines.html#tests-requiring-special-headers) for the wpt stuff.

**Comment by gsnedders** [comment]
Some files ([insert list here]) will have their headers changed until https://github.com/w3c/wptserve/issues/90 is resolved.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5467; please continue all discussion there.
