### ISSUE TITLE
Add a real lint tool

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-test#926]
We want to move in the direction of having no build warnings, and really want to avoid regressing anything we currently have. We probably also want to add further lint checks.

**Comment by gsnedders** [comment]
I don't know if we just want to take wpt's lint tool. We probably want something more because we want to make sure the flags we have are what we expect.

**Comment by cvrebert** [comment]
> We probably also want to add further lint checks.

e.g. Check that files referenced by `<link rel="match">` actually exist.

**Comment by gsnedders** [comment]
Note the build system currently gives warnings for those.

**Comment by cvrebert** [comment]
Ah, I had assumed that the linter was what powered @syncbot, which doesn't currently issue a warning in said case.

**Comment by plinss** [comment]
@cvrebert correct @syncbot is powered by the Shepherd tool. Adding reference link tests should be easy.

**Comment by gsnedders** [comment]
Can we reduce the multiplicity of tooling we have around?

We currently have, as far as I'm aware, three different lint systems:

 * wpt's
 * Shepard's
 * CSS build system

Ideally we should have one. Really what we check for csswg-test should be a superset of the rules of wpt's lint tool, I think.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5468; please continue all discussion there.
