### ISSUE TITLE
Built copies of white-space-processing-00{5..7} are broken; asis is unsupported

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-test#937]
These are all tests for CR behaviour around the `white-space` property.

Note that "\x0D\x0A" (as a literal byte sequence; i.e., CRLF) gets converted by an XML parser to "\x0A" (i.e., LF). To get around this, the tests all represent CR and CRLF by their character references. This is comparable to the situation in HTML, though there also a lone "\x0D" gets converted to "\x0A".

However, the build system replaces these character references with the characters they represent. In HTML and XHTML cases, this breaks all three tests.

It appears the `asis` flag doesn't work any more, too, as in principle this would avoid this. (Really serializers should just avoid breaking this, IMO!)

cc/ @plinss

**Comment by plinss** [comment]
Will take a look. It's entirely possible that I never got around to making the asis flag work in the first place (or i broke it during a build refactor).

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5470; please continue all discussion there.
