### ISSUE TITLE
CSSOM-Views is almost entirely untested

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-test#942]
Moving @roccallahan's bug from https://github.com/w3c/web-platform-tests/issues/2304.

> E.g. `getBoundingClientRect`, `getClientRects`, `inner/outerWidth/Height`, `pageX/YOffset`, `offsetLeft/Top/Parent`, `clientWidth/Height`, and everything in `GeometryUtils`.
> 
> Gecko has mochitests for these, most of which could quite easily be converted.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5471; please continue all discussion there.
