### ISSUE TITLE
Tests with alternative references

### ISSUE THREAD

**Issue by hrj** [w3c/csswg-test#943]
There are some tests with alternative references, such as the ones in this commit: https://github.com/w3c/csswg-test/commit/099394fba2a7b475846e2495b4a0ab5e4ef02eca

The corresponding entries in `xhtml1/reftest-toc.xht` have an extra row, but the extra row contains a repeat link. Is the intention of the second row to show the alternative reference link? If yes, then it needs a fix.

**Comment by plinss** [comment]
Yeah, the second row should list the alternate reference. Will take a look.

**Comment by hrj** [comment]
@plinss Thanks for looking.

Just found another test which has an alternate reference: `numbers-units-015.xht`

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5472; please continue all discussion there.
