### ISSUE TITLE
The reference for universal-selector-002.xht is broken

### ISSUE THREAD

**Issue by hrj** [w3c/csswg-test#944]
The [test](https://github.com/w3c/csswg-test/blob/master/css21/selectors/universal-selector-002.xht) expects green only for the first child, but the [reference](https://github.com/w3c/csswg-test/blob/master/css21/selectors/universal-selector-002-ref.xht) has green color on the entire body element.

**Comment by Ms2ger** [comment]
Would appreciate your review of https://github.com/w3c/csswg-test/pull/946.
